### PR TITLE
Added getPowerMultiplier and setPowerMultiplier to API mage.

### PR DESCRIPTION
**Pull request by dumptruckman**

### CODE REVIEW

**Comment by NathanWolf** [comment]
Just make sure when you use this in an action that it gets reset :)

**Comment by dumptruckman** [comment]
My plan was to make a buff that increases the multiplier for a time. Is this a bad idea?

**Comment by NathanWolf** [comment]
I wouldn't say it's a bad idea, as long as you're certain it gets unset. I guess worse-case it's not persistent so it'll reset on relog.

Mainly I stopped using "Power" myself because the results are kind of unpredictable- you can do some tweaking in config.yml, but power affects too many things. I kind of replaced my use of wand power leveling up with spell leveling instead for a more controlled approach.

For instance, power doesn't just affect the damage action scaling, it also makes the radii of AOE and Volume actions bigger, increases range on all spells, etc. You could turn all but damage off in configs though if you just want to use it as a damage multiplier.

**Comment by dumptruckman** [comment]
Good to know!

**Pull request merged**
