### PR TITLE
Consistent imports

### PR DESCRIPTION
**Pull request by killme**
Make import order consistent, and enforce it using checkstyle.

This may require you to reconfigure your IDE, or checkstyle will not like you.
These are the eclipse settings that I use: http://i.imgur.com/gKKji5k.png

(Previously imports seemed to be pretty much all over the place http://i.imgur.com/oEHWOUr.png)

(Unlike the other PR, this one should be merge ready)

### CODE REVIEW

**Comment by NathanWolf** [comment]
Nice, thank you!  This is ready to merge, I assume? Not going to squash this one.

I think I got my IDE to mostly match, but can Eclipse do blank lines? I kind of like having the core imports separate from other packages like this:

https://i.imgur.com/IVNPfkM.png

It looks like from these commits I should put a blank line between each entry in here (com, org, net)- does that seem right?

Also a pet peeve of mine is when my IDE collapsed a small number of imports into a * import, I have that turned off and I'm hoping Eclipse doesn't do that (doesn't look like it)?

**Comment by killme** [comment]
Eclipse generally puts lines around any group, so you would have more blank lines on eclipse then.

The problem with that though is that checkstyle does not support it. As it is rather limited in this department. (See the checkstyle.xml file)

**Comment by ljacqu** [comment]
Just to put it out there – do you really want a failing build if some import doesn‘t follow some order? 
I understand disallowing star imports and checking for unused imports (although the latter causing the build to fail also seems extreme) but you‘re probably shooting yourself in the foot if you want your build to fail if an import is out of order.

**Comment by killme** [comment]
We did this primarily to avoid merge conflicts and weird diffs caused by differences between me and nathan's IDEs. As with this commit there is only one way to write them down, merge commits on imports should be less frequent. Since we can just configure our IDEs to produce the correct output, I don't really see how this would be a problem.

Apart from that, this not only breaks the jenkins build but also locally, so you get notified immediately if something's off.

**Comment by NathanWolf** [comment]
I get what you mean, @ljacqu , I'll admit it's a little odd to me for builds to fail for style reasons, but I kind of like the idea and at this point it's basically just @killme and I in this code.

As long as both of our IDEs handle it properly it shouldn't be an issue.

I'd much rather have to take a minute to adjust some style because the build broke, than deal with some merge conflicts.

**Pull request merged**
