### PR TITLE
Include README

### PR DESCRIPTION
**Pull request by FlyingPikachu**
See #471

### CODE REVIEW

**Comment by killme** [comment]
You should update the existing readme in `MagicPlugin/README.md`
And could you squash your commits?

(Also, please note that if you make a pull request github will automatically add new commits on the branch to the request, so you generally want to use a branch different than `master` when opening a PR)

**Comment by NathanWolf** [comment]
Agree on the "don't PR from master", that's going to make a big mess.

It's easy for me to rebase when pulling though so that part's not a big deal.

And actually I think having a README in the root is a good idea, since it shows up nicely on the github landing page. I should maybe merge the two, though.

**Comment by FlyingPikachu** [comment]
@killme Yes, I learned about how it does that automatically from my last PR. Wasn't aware of that other file, but now that you mention it I can't even tell if this is top-level (although as @NathanWolf points out that's what I'm going for). I'll just make a new request.

**Comment by FlyingPikachu** [comment]
Or that lol

**Comment by killme** [comment]
The readme wasn't top level because we never bothered moving it after merging the API and the plugin repos.

**Comment by NathanWolf** [comment]
Meeeeeemmmmorrrieeeeessss

**Pull request merged**
