### PR TITLE
Added ModifyAttributeAction

### PR DESCRIPTION
**Pull request by grisstyl**
Moved to separate branch and removed header. Irresponsible Tyler forgets once again that branches are the way to go. 

@NathanWolf @killme let's outline the changes that we need to make to this PR before it can be merged. I understand that we want support for equations but I'm not clear on the implementation for that.

EDIT: Or not. Next commit, I swear.

### CODE REVIEW

**Comment by killme** [comment]
I am not a 100% up to date on what these attributes do exactly.
Would it not be more appropriate to register modifiers like in vanilla?

**Comment by NathanWolf** [comment]
Hm, that's not a bad idea. It would be slightly less flexible, but probably for 99% of uses cases an offset and multiplier would be plenty.

Unfortunately the ModifyProperties action is already "out there" with arbitrary equation support so that'd be a bit of a breaking change. I'll have to think about it.

**Comment by grisstyl** [comment]
To what are we referring? This action is for incrementing or decrementing the internal properties of Magic. What is @killme proposing?

**Comment by NathanWolf** [comment]
I think he's offering a solution to the stacking problem, which is more of an issue for ModifyProperties, or if you were to extend this action to allow more arbitrary changes (like strength = strength x 1.5) instead of just incrementing/decrementing.

Vanilla MC attributes generally aren't set directly, they are modified with modifiers, which can be additive or multiplicative. These modifiers go on a list, and the working attribute value is computed from the base value and the list of modifiers. This way you never have an issue of "oops I changed the value and forgot to change it back".

**Comment by grisstyl** [comment]
Okay, I think I understand. Thank you for clarifying.

**Comment by NathanWolf** [comment]
No problem! Now... unfortunately, that all said, I do think the ModifyProperties action actually covers this already. It's got a bug I need to fix (attributes don't actually update) but I think that would've affected your action too... ?

For instance, this basically does the trick:
```
modifystrength:
  actions:
    cast:
    - class: ModifyProperties
  parameters:
    target: self
    modify_target: player
    modify:
    - property: "attributes.strength"
      value: "x + 1"
    undo: 300000
```

So I hate to say it, but this action may not be needed at all.

There is still the bigger issue of safely applying temporary modifiers, but that is what the status effect system is meant to solve, if I ever get around to that.

**Comment by grisstyl** [comment]
Hm, I see what you mean. If you decide to not merge I'll take note of this approach on the Attributes wiki page. However, I'll make the case that this action is to ModifyPropertyAction as HatAction is to WearAction. It isn't entirely necessary, but it simplifies the approach and reduces the verbosity of the configuration making it very clear what it does.

If we could get the equation support baked into this action I think a case could be made for its viability.

**Comment by NathanWolf** [comment]
Hm, perhaps but I’d still prefer to not have the code duplication. Maybe we could add a simpler interface for setting attributes.

Hat action is actually deprecated ;)

**Comment by grisstyl** [comment]
Hmm, okay. Sounds like an alright solution to this.

**Pull request closed without merging**
