### PR TITLE
Remove empty class

### PR DESCRIPTION
**Pull request by FlyingPikachu**
Although empty, the presence of this class causes Eclipse IDE to assign an incorrect classpath when cloned.

### CODE REVIEW

**Comment by NathanWolf** [comment]
So I am fine removing the empty class, not really sure how or why that's still in there.

The pom changes, though, I do not like. I'd like to keep all of the dependencies separate, the API and Compatibility libs don't need all of that. Does Eclipse have some kind of issue with multi-module Maven projects or something?

**Comment by FlyingPikachu** [comment]
@NathanWolf Didn't intend for my other commits to be a part of this PR - apparently git is deciding that for me.

To answer your question, yes and no. Maven integration in Eclipse (and Eclipse in general) is very picky and doesn't like something about your setup, causing the IDE to fail populating integrations from the Magic child pom. I've spent my last two days off work trying to figure it out and failed. While it is possible to _manually_ download each plugin and _manually_ add them to the build path, this causes a [quirk with bStats](https://www.spigotmc.org/threads/help-shading-bstats.358174/#post-3301509) rendering the plugin unable to compile, at least locally. The fact that MagicPlugin uses several dependencies in which more recent builds have removed/changed/deprecated methods (Vault, Elementals, et al.), this can be challenging as the dev must ensure to match version numbers.

I'm quite certain that the commits I've just finished pushing are the best and only workaround to getting Eclipse to play nice with your project without affecting other environments. See Marquee's answer to [this SO question](https://stackoverflow.com/questions/4859825/how-to-add-maven-managed-dependencies-library-in-build-path-eclipse) to understand why it works. Considering MagicPlugin has over 40 dependencies (including libraries) and you're the only one working on it, I feel it's pertinent to the longevity of the plugin to make it easily clone-able on the world's most popular Java IDE (although, increasingly, the most annoying one).

If you decide to accept this PR in its current state, I've tested that cloning to Eclipse will be as simple as the following:

1. Clone to Eclipse IDE with JDK 8. Add as Java Project.
2. Right-click project -> Configure -> Convert to Maven project
3. Compile with "clean package install" or appropriate goal

Without my latter changes, one _might_ be able compile MagicPlugin by, again, downloading all dependency jars through the interwebz, as well as manually modifying the classpath and copying the Metrics class for bStats into an org.bStats package (which I didn't resort to as I gave up at that point, hence "_might_").

**Comment by killme** [comment]
Please don't merge this until I get a chance to look at it.
I also use eclipse and I haven't had any issues thus far.

**Comment by FlyingPikachu** [comment]
@killme What's your OS? Care to share your classpath?

**Comment by killme** [comment]
Ubuntu 18.04. I didn't change anything related to my classpath.

**Comment by killme** [comment]
I think the problems with the missing integrations might be caused with the strict "do not download snapshots" that we have configured in this repository to speed up builds.
Though, if you simply run `mvn clean install` manual, these should all be downloaded and available locally.
Then you can run "import maven project" in eclipse as usual.

If you're still having issues, feel free to message me on IRC or Discord.

**Comment by FlyingPikachu** [comment]
Thanks for the reply @killme. Perhaps this is Windows-only then, but it goes without saying that this issue shouldn't be overlooked if you all intend for most others to be able to contribute.

Not sure where that configuration is located, but I can say that doing Right-click project -> Maven -> Update Project... and checking the "Force Update of Snapshots/Releases" box has no visible effect.

Attempting to `clean install` straight from the get-go results in compilation failure:

> [ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] C:\Users\Dylan\git\MagicPlugin\MagicAPI\src\main\java\com\elmakers\mine\bukkit\api\event\LoadEvent.java:[3,1] An unhandled exception was thrown by the Error Prone static analysis plugin.
Please report this at https://github.com/google/error-prone/issues/new and include the following:
error-prone version: 2.3.2
BugPattern: BadImport
Stack Trace:
java.lang.BootstrapMethodError: call site initialization exception
  	at java.lang.invoke.CallSite.makeSite(CallSite.java:328)
  	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:296)
  	at com.google.errorprone.bugpatterns.BadImport.isAcceptableImport(BadImport.java:133)
  	at com.google.errorprone.bugpatterns.BadImport.matchImport(BadImport.java:82)
...

Fixing this results in an error for ReturnMissingNullable, which ultimately led me to setting the following flags in the parent pom to allow compilation:

><arg>-Xep:BadImport:OFF</arg>
   <arg>-Xep:ReturnMissingNullable:OFF</arg>

Now that said, although it compiles, the IDE _still_ reports errors as the integrations remain unpopulated. [Here's a screenshot depicting what I mean after converting to Maven project.](https://i.imgur.com/pEWEIH2.png) Refreshing/updating makes no difference because dependencies are not present in the parent pom. Overall, this makes the project difficult to work with unless the dev were to disable error underlining, which shouldn't be advisable. In summary, your way of doing it means:

1. Clone to Eclipse IDE with JDK 8. Add as Java Project.
2. Compile with "clean install"
3. Windows(?) users must manually add 40+ dependencies to build path & modify their classpath

Not good.

@NathanWolf Thanks for removing the empty class. Please note that the dependency for prior versions of that class is still present, however. See d8e411069e69b3ed0fd4671985916295de92598c from this PR

**Comment by NathanWolf** [comment]
Thanks for the catch on that dependency being in there! I removed it.

I do have to agree with @killme though this seems like it must be something specific to your environment, especially if it's going wrong with just a clean install.

Have you tried taking Eclipse out of the picture completely? Just clone and `mvn clean package`?

That's what build servers do and so far it hasn't seem to break for anyone, though I guess it's unlikely anyone is running CI on a Windows machine, either.

https://gist.github.com/NathanWolf/1720e55c8ed7f2b7674453872cf57d9b

Just as a second opinion I cloned fresh myself and built and it seems fine, though I'm on Mac OS here.

**Comment by FlyingPikachu** [comment]
Good point. I'll grab my Windows laptop that's never seen Eclipse and try a fresh install of everything.

However, you're right that I'm not running CI on Windows, so like many Win users I don't have Maven set up for command line. Until now, the built-in integration with Eclipse has been sufficient for me. Your suggestion might work if I set it up, but the issue remains that other Win users cloning the project may be initially confused as to why their IDE is flipping out.

By the way, I'm pushing for this because I'd like to try regularly contributing to the project. Could be nice to see a deeper integration with Quests down the road.

**Comment by killme** [comment]
You shouldn't import it as a java project, but as a maven project.
That way it will create an eclipse project for every maven module.
Otherwise it won't be able to pick up on the pom files of the modules.

**Comment by FlyingPikachu** [comment]
@NathanWolf Installed the latest Eclipse (2018-12) on that laptop and got identical results. If it's a bug with Eclipse, at least it's consistent! I wouldn't call having them in the parent pom "wrong" but I understand your concern. Other options include having the API as a separate project or using a distribution pom to manage dependencies.

@killme You're right, it seems the path less traveled (for me) was correct. Importing directly as a Maven project first gave me these errors:

maven

Then I was forced to install the Checkstyle plugin for Eclipse. Afterward, everything seems hunky-dory as the integrations are populated and the IDE is happy, except for the following:

antrun

I'm guessing that can be ignored, though, as the project compiles (after I again tweak the flags from earlier). Thanks for clearing this up! Will submit a new PR for the flags and perhaps a README with compile instructions so no-one repeats this mess.

**Comment by killme** [comment]
The dependencies are only relevant for the plugin module (/project) in our case. It would not make sense to put them in the parent project, where they would be exposed to the api project as well.

Generally speaking you can ignore those "not covered by lifecycle configuration" warnings in eclipse, as these plugins are not necessary to build a correct jar.

Are you on the latest master? As changes to the errorprone flags shouldn't be necessary. Everything builds fine on my desktop and two different CI systems.

**Comment by FlyingPikachu** [comment]
@killme Yes, latest master. Just deleted and cloned again to be sure. Here's the initial error:

https://pastebin.com/nMgJ6Wyz

And after setting `-Xep:BadImport:OFF`:

https://pastebin.com/NwbnfPVk

Only after setting `-Xep:ReturnMissingNullable:OFF` would it compile. I saw "would" because it looks like the commit 4 hours ago from @NathanWolf may have broke something:

https://pastebin.com/hAU6LYvn

**Comment by killme** [comment]
Those first two errors look like ErrorProne bugs.

The last one is probably because of a change Nathan just made related to maps.

**Comment by NathanWolf** [comment]
It's definitely weird that ErrorProne is breaking your build. I did just go in and clean up all of the warnings, but they've always just been warnings.

That 3rd paste looks like you're maybe not rebuilding everything. The signature on getMap changed to an int so there shouldn't be any lossyness there.

Try rebuilding from the parent pom, in the root folder just do `mvn clean package`

Sorry you're having so much trouble with this, I've only ever had a handful of people clone+build the plugin (to my knowledge) but I've never had anyone report these kinds of problems before.

**Comment by FlyingPikachu** [comment]
Thanks for the quick replies!

Rebuilding from the parent pom does not fix the ErrorProne issues, but _did_ resolve the getMap issue. Much appreciated. That said, I'm submitting a new PR that includes a README with compile instructions.

**Comment by NathanWolf** [comment]
I'd agree with @killme that something is broken with your ErrorProne install... not sure what to do about that. Does turning off the BadImport check fix that for you?

I'm not certain I want to turn that off but if it's the last of your issues at this point then I'm willing to go for it :)

**Pull request closed without merging**
