### PR TITLE
Towny and PreciousStones support

### PR DESCRIPTION
**Pull request by Boosik**
Full PvP/Build support for PreciousStones
Partial support for Towny (PvP is always false, Build is allowed only if player owns townblock and in wilderness)

You need to add configuration options to default config as I didn't add it to the code. Also I could not find Towny repo, so pom entry will be invalid (I added towny artifact to my local maven repo manually).

### CODE REVIEW

**Comment by NathanWolf** [comment]
Thank you! I will definitely want to merge this- and I guess host Towny in my own repo, if I can. Otherwise this will break anyone else trying to build, I want to stay Mavenized.

**Comment by NathanWolf** [comment]
Ok, taking it- I'll deal with the Towny issues separately. This is too good to pass up! 

Thanks so much, again :)

**Comment by Dr00bles** [comment]
Ooooh what is this...? this looks epic!

**Comment by NathanWolf** [comment]
Some kind person added support for those two plugins to Magic- so if you used Towny or PreciousStones,  Magic would respect perms like it does for Factions and WorldGuard.

**Comment by NathanWolf** [comment]
Ok, @Boosik - your PR is now part of the official build! You can grab dev build#586:

http://jenkins.elmakers.com/job/MagicPlugin/586/

And hopefully not have to maintain a fork anymore :)

I took your PR as-is, I will probably want to review it and add the config options you suggested, but at this point I'm so happy to be able to support these plugins that I am just trusting you there.

I managed to Mavenize Towny (wow, what a pain!) and am now hosting several dependent projects (a few of which I also had to Mavenize) ... but this should mean Magic is still fully "pull and build"'abe with Maven.

Thanks again!

**Comment by Boosik** [comment]
No problem! Your plugin is great and it's honor to make it even better.

Thank you for your plugin.

**Pull request merged**
