### PR TITLE
Add custom Material set

### PR DESCRIPTION
**Pull request by killme**
Add support for data values to the material system.
`stone` will match all variants, but `stone|0` will only match regular stone.
In the future we'll be able to add more complex material filters if needed.

In order to make this work we basically replace `Set<Material>` with `MaterialSet` all over the code base.
Sadly this will break the API.

I have also deprecated a lot of methods that take a `Material` rather than a `Block`.

**DO NOT MERGE YET** I am still testing this, but have posed this for early feedback.

### CODE REVIEW

**Comment by NathanWolf** [comment]
This looks nice- I didn't fully read, it's a huge commit, but skimming it I see the idea, and it looks like you covered the weird edge cases like wildcards and negations.

People have asked for this quite a few times so I think it'll make most happy. Any API breakage is probably ok since you're the main (possibly only) real API consumer at this point. PWMC does a bit but nothing this deep, I think.

My main hesitation with finally implementing this, however, I need to mention. They've been threatening to kill data values for a while now, and sounds like it's actually happening in 1.13. Is all of this going to break or be pointless once that's out? Or we would just have to pivot it to support stuff like "wool:red" instead?

**Comment by killme** [comment]
I am aware of the 1.13 changes, which could make a lot of this not as important as it is right now.
As wool etc, will all be different materials.
But this will still be useful to support differentiating between block states or custom matchers.

I don't see how this would break in 1.13, given that `MaterialAndData` is updated, and perhaps some backwards compatibility to migrate old data values.

**Comment by killme** [comment]
I have un-broken the API and simplified some things (like adding `fromConfig`).

I will run this on my test server to see if anything will break.

**Comment by NathanWolf** [comment]
Hey @killme how's this looking?

I don't want to rush you but it looks like I'm already causing conflict headaches for you.

I think that's going to get a lot worse soon- I'd like to add a bunch more material sets to cover some hard-coded Material checks in some of the BaseSpell/etc classes. I'm hoping to ease the painful transition to 1.13 in doing so. (Nearly all of the hard-coded Material constants break in the API preview)

But basically I don't want to do any of that until we can merge this PR in since I think it'll just create more merge issues for you.

**Comment by killme** [comment]
I'll try to get some final testing with the data values done tomorrow.
(I had assigned the task to my move guys, they're not always as fast)

Thus far I have primarily been running it to see if anything would break, which does not seem to be the case. So with that final testing done I think we can safely merge this.

**Comment by killme** [comment]
I tried rebasing onto master, but I am getting compiler errors on master.
(And so does my CI)

```
[ERROR] Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicConfigurableExecutor.java:49: error: no suitable constructor found for EquationTransform(no arguments)
[ERROR] EquationTransform transform = new EquationTransform();
[ERROR] ^
[ERROR] 
[ERROR] constructor EquationTransform.EquationTransform(String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor EquationTransform.EquationTransform(String,String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor EquationTransform.EquationTransform(String,String...) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor EquationTransform.EquationTransform(String,Set<String>) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicConfigurableExecutor.java:[50,21] error: cannot find symbol
[ERROR] 
[ERROR] could not parse error message:   symbol:   method setQuiet(boolean)
[ERROR] location: variable transform of type EquationTransform
[ERROR] Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicConfigurableExecutor.java:51: error: cannot find symbol
[ERROR] transform.addVariable("x");
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   method addVariable(String)
[ERROR] location: variable transform of type EquationTransform
[ERROR] Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicConfigurableExecutor.java:53: error: incompatible types: void cannot be converted to boolean
[ERROR] if (transform.setEquation(value)) {
[ERROR] ^

**Comment by killme** [comment]
Also getting an error in BaseMagicConfigurable line 314:
```
    @SuppressWarnings("unchecked")
    protected @Nonnull Map<String, Object> getSpellLevels() {
        Object existingLevelsRaw = getObject("spell_levels");
        if (existingLevelsRaw == null) return new HashMap<>();
        Map<String, Object> spellLevels = null;

        if (existingLevelsRaw instanceof Map) {
            spellLevels = (Map<String, Object>)existingLevelsRaw;
        } else if (existingLevelsRaw instanceof ConfigurationSection) {
            spellLevels = NMSUtils.getMap((ConfigurationSection)existingLevelsRaw);
        }

        return spellLevels;
    }
```

You declare it as `@Nonnull` but there is a path that returns null.

**Comment by NathanWolf** [comment]
Ugh, sorry- I just pushed a fix for getSpellLevels returning null.

For the EquationTransform thing, I think you just need an updated EffectLib- I'm not sure why it didn't pull that from my Maven repo though?

**Comment by NathanWolf** [comment]
Just double-checked my CI, this build should be the one you need: http://jenkins.elmakers.com/job/EffectLib/121/

So, let me start by saying I like this PR, I think it's cleaner and more flexible that just using Set<Material> everywhere.

But I do have a few concerns:

1. After spending some time with the 1.13 API I'm a little worried that all of this will soon be irrelevant. Bukkit's own MaterialData has been deprecated and there's really no need for it anymore, outside of complexities like TileEntity data as part of a block MaterialAndData. Everything that would normally be a Material,data pair is now just its own Material enum.

This is the big one for me, but since you've already done the work maybe it doesn't matter as long as 2 and 3 below are covered.

For these points, please forgive me as I haven't pulled your branch to look at it properly. I've just been reading through the diffs here, which is definitely not ideal. I can't actually find the concrete implementation of MaterialSet, for one :\

2. My biggest worry for this would be performance concerns, as this is the main reason I never tried to do this myself. Material sets are queried extremely frequently (think of an in-flight projectile or a huge construction batch). I worry if this now means we have to build a String key for every block we need to check, this would feel much less efficient than checking a Material against a HashSet.

I can't think of a good way to profile the performance impact, but if you have any ideas on that I'd appreciate it putting my mind at ease a bit.

3. A minor concern about a TODO note I read regarding referenced material sets. We need to make sure something like "transparent,air,glass" works, where "transparent" is itself a material set.

So mostly I'm worried about you having done all this work, and then some time in the future I decide we don't need it anymore (it's really looking like I will need to make a version of Magic that is not backwards compatible once 1.13 hits...) and strip a lot of it out for performance reasons. However, I do think the actual interface is much cleaner so hopefully it would only be a matter of gutting the internals so internally it's still just doing HashSet<Material> checks.

Ok I had to get all that off my chest, let me know what you think, and if there's anything else I can do to help with these conflicts. Thanks!

**Comment by killme** [comment]
Regarding 1. I think it will help as we can eventually add support for things like the vanilla material collections. So we could just write something like `@wood` and it will add all wood variants. I have not tried out the 1.13 API yet so I am not sure how easy it will be.

Regarding 2. I am not doing any sort of string interpolation at runtime. Ideally all unions of material sets etc are done at configuration load time. Right now, because of my unfamiliarity with magic wrappers around block data, some things are `O(n)` where they could be grouped by a key. But since most material sets are pretty small this doesn't matter all that much. And regular material checks are actually still `O(1)`. So TL;DR there should be no performance impact if you are not using the data values. And if you are, the impact is most likely minor.

You can find the implementation in the `MaterialSets` class. I have decided to keep the implementation of the sets and implementation detail, so we can easily extend them or optimize them when needed.
Link to class: https://github.com/elBukkit/MagicPlugin/blob/material-set/Magic/src/main/java/com/elmakers/mine/bukkit/magic/MaterialSets.java (Github doesn't show this in the diff by default as it is quite large.

(Negations are also supported but are not "unpacked" as nicely as non negated sets)

Regarding 3. This is actually implemented.

**Comment by NathanWolf** [comment]
Sounds great, thank you for easing my mind!

**Comment by killme** [comment]
Seems to work, will rebase and squash.

**Comment by killme** [comment]
Spoke too soon. o.o

**Comment by NathanWolf** [comment]
I apologize that I've been letting this sit for so long. I've been taking a look at the branch and I really have to admit I have some hesitation- mainly that all of this seems like it's going to be irrelevant in 1.13

For testBlock checks, it won't matter at all anymore. MaterialAndData.is(Block) only checks Material and data- and data is going away. I suppose we could extend that to also check certain metadata, but I'm having a hard time thinking of a good use case for that... targeting specific player skulls? Orientations of rotatable blocks?

Similarly for items, data is going away and only durability remains. But is there a good use-case for matching an item with a specific durability?

I will be honest here and say that I am wanting to hold off on this until I've branched code for 1.13 - this seems like a good fit for 1.12 and lower, but I worry it is adding a lot of complexity for little gains once we hit 1.13.

Feel free to convince me otherwise .. it's lot of nice elegant code, but the amount of change is somewhat overwhelming and if I look ahead to 1.13 feels a little like fixing something that isn't (or won't be) broken.

**Comment by killme** [comment]
Is fine by me, I primarily implemented this because we needed it right away. We can reconsider this after 1.13, until then I'll just keep this branch up 2 date as we're using this in production.

**Comment by NathanWolf** [comment]
I appreciate your flexibility, but I don't really want you to have to stay branched!

I'll give this branch a good playthrough to make sure there aren't any odd edge cases you all might not run into. If it looks good, I'll merge it in after I release 7.3.

I do like the changes, and I think if needed they can be adjusted or pared down for 1.13. I'm guessing I will need to maintain separate branches for Magic 7 (1.12) and 8 (1.13) for a while, if I can't make it backwards compatible, so it'd probably be easier for them to both have these changes as a base.

I also noticed you've already done quite a lot of what I was initially planning to do for 1.13, mainly replacing a lot of the hard-coded material checks with sets, which is a great step in the right direction. Rather than re-do it the old way and give you merge headaches I think I will just take your changes.

Thank you!

**Comment by NathanWolf** [comment]
Thank you!

**Pull request merged**
