### PR TITLE
Update stairs.yml

### PR DESCRIPTION
**Pull request by PhvntxmX**

### CODE REVIEW

**Comment by NathanWolf** [comment]
The diffs are confusing me (things moved around), did you remove any stairs here? It seems like some of the legacy ones were removed, and sadly (for now) we have to keep them. If you can easily diff this and see that'd be helpful, if not I can probably fix it up after merging in.

**Comment by PhvntxmX** [comment]
No, there is just all things. I've added all stairs that editor is suggested to me

**Comment by PhvntxmX** [comment]
And I am checked them now, all stairs that marked is 'removed' is still here. So I it's not gonna break anything

**Comment by NathanWolf** [comment]
Perfect, thanks for confirming!

**Pull request merged**
