### PR TITLE
Buffable armor

### PR DESCRIPTION
**Pull request by PhvntxmX**
I made it so that one piece of armor protects against one type of damage
Helmet - overall
Chestplate - physical
Leggings - fire
Boots - fall

### CODE REVIEW

**Comment by NathanWolf** [comment]
I like the idea of this. I think it might be nice if you could buff the wand then to increase magic damage, maybe?

The thing that's missing that I would need to implement is wiping protection on wands. Ideally I'd refund them the SP, too, but not sure I can easily do that.

**Comment by PhvntxmX** [comment]
I thought about it, but I was not sure if you like it. So, yeah, I can make this

**Comment by NathanWolf** [comment]
I definitely like the idea, but have to be careful about changing things like this since it either takes away things players have already earned, or leave players with things that players can no longer earn. Neither is an ideal situation.

**Comment by NathanWolf** [comment]
I also imagine if I allowed this I'd have to rebalance protection a bit. Probably someone who maxed out all 4 armor pieces would have an OP amount of protection.

**Comment by PhvntxmX** [comment]
Gonna make another PR

**Pull request closed without merging**
