### PR TITLE
2nd part of additions/changes to survival spells

### PR DESCRIPTION
**Pull request by PhvntxmX**
1) Rebalanced silence spell. Now has 3 levels:
Upgrade decreases manacost and cooldown, increases duration.

2) Sunstrike now has 3 levels:
Upgrade increases max damage(10/20/40), decreases delay.

3) Rework shuriken again:
Now uses this strange mechanic to target same entity multiple times.
Tried also ignore_hit_entities, but it causes strange behavior there projectile is "stuck" in the same entity, damaging him multiple times.

4) Rework meteor spell:
Now summons one big meteor, that shoots smaller meteors when flying. Big meteor deals 5x damage and breaks blocks in a 16 block radius.
Has 2 levels. Upgrade increases small meteor count, decreases cooldown.

5) Rebalance harden spell. Now has 5 levels:
Upgrade increases duration. Each level has different block type (stone/stone bricks/smooth stone/polished blackstone/obsidian).

6) Rebalance petrify:
Increased duration (4/6/8 seconds at each level), increased manacost (120,100,80 points at each level), added slow digging effect.

7) Workbench now has 4 levels:
Upgrade decreases cooldown(20,10,5,0 seconds at each level) and manacost(80,40,20,0 points at each level).

### CODE REVIEW

**Comment by NathanWolf** [comment]
This sounds really nice

I do have some concerns about backwards-compatibility, though- like the new blocks that harden uses. I think that'll break for any pre-1.16 servers

I like the idea but I think if we really want to do that we might have to add the current versions to legacy configs .. kind of a pain. I can probably do it, but can you think of any other cases like that where you may be using modern blocks or items?

**Comment by NathanWolf** [comment]
Also, we should add sunstrike to a path? It sounds cool.

**Comment by PhvntxmX** [comment]
Yeah we can do it

**Comment by PhvntxmX** [comment]
So about modern blocks, I don't think I gonna use them anywhere else

**Comment by PhvntxmX** [comment]
Oh, also I made a mistake in a description. Big meteor breaks blocks in a 10 block radius, similar to the Nuke spell

**Comment by NathanWolf** [comment]
Wow that sounds kinda OP, I'll have to try that out :D

And OK I don't think it's a huge deal to add some overrides for harden to the legacy version configs.

**Comment by PhvntxmX** [comment]
So, equivalent of smooth stone and polished blackstone is a cobblestone. So you can replace both of them with cobblestone

**Comment by PhvntxmX** [comment]
And if meteor seems too OP, you can increase cooldown to 1.5 minutes at 1st level and 1 minute at 2nd level

**Pull request merged**
