### PR TITLE
ClearChatAction

### PR DESCRIPTION
**Pull request by grisstyl**
Added ClearChatAction as Nathan and I discussed on RPG MC Central. I put in the `message` and `message_count` fields in there because I believe that there may be some use cases for people who wish to fine tune their chat clearing.

As per Nathan's suggestion, I removed the `target_source` and `global` fields so that you can simply pair this action with compounds without confusion.

### CODE REVIEW

**Comment by grisstyl** [comment]
Whoops, apparently I didn't pull since @killme put on some last touches and committed! Feel free to resolve that conflict.

**Comment by NathanWolf** [comment]
Hm I think you may have to re-do this, sorry!

You'll need to pull first then add ClearChat back... as it stands now this PR includes all of the Chat action changes, too, which will make for a messy merge at best.

It should just be one commit, adding the ClearChat action.

If you'd prefer you can just paste the action code to me and I'll add it in, but I'd prefer a clean PR so your name gets attached in the commit log :)

**Comment by grisstyl** [comment]
Yeah, this got messy quick. Not sure why. Thank you for your honest feedback though! I'll clean up the PR and resubmit.

**Comment by NathanWolf** [comment]
For future reference, PR's are best done from a branch- that way when it's merged in you can update your master without worrying about conflicts.

Otherwise this sort of thing can be very difficult to rectify- if you don't have any other changes it may just be easier to reset your master to the upstream repo (this one) and add your new code back in. I've gotten stuck here before, too.

**Pull request closed without merging**
