### PR TITLE
Fixed melon block in 1.13

### PR DESCRIPTION
**Pull request by Yanis48**
Also removed the useless semicolons

### CODE REVIEW

**Comment by NathanWolf** [comment]
Thanks very much!

**Comment by Yanis48** [comment]
Pretty sure you forgot to merge :p

**Comment by NathanWolf** [comment]
Ummmm whoops :( Really?  Does look like it... sadly I can't merge now because you deleted the branch too!

If you can undelete please do... otherwise if you don't want author credit I can just copy the diffs myself.

**Comment by Yanis48** [comment]
Do it! I don't think the change is enough important to consider credits ^^

**Pull request closed without merging**
