### PR TITLE
Add error-prone warnings

### PR DESCRIPTION
**Pull request by killme**
**This is a WIP, do not merge yet**

Using google's error-prone javac plugin we can generate warnings for common bugs, similar to findbugs.

- Configured it to fail builds in the case of unused imports.
- Configured error-prone to require an `@Nullable` annotation in order to make `return null;` work.
  - Annotated all functions that can return null with `@Nullable`
  - Made `getMage` throw rather than return null, as it was recently annotated `@Nonnull`. Should we just fix the annotations back to `@Nullable`?

I can also configure it to require `@Nullable` on fields, but considering most of the existing code relies on null fields, this would probably be fairly pointless. I guess we should just annotate fields that are always guaranteed to be non null with `@Nonnull` and other fields `@Nullable` for new code, and ignore old code for now.

Another thing I ran into is the common pattern of returning null when arguments are invalid. This leads to a lot of things being `@Nullable` for only that reason, which makes it not as useful as a tool as it could be.

Anyways, this will hopefully improve the quality and maintainability of the codebase. And make my IDE go less crazy with warnings `:P`. If you have further suggestions for warnings I should configure, I would be glad to do so. (As of now I only raised the severity of two patterns from http://errorprone.info/bugpatterns to make the build fail)

In a future PR I might also look into using something like checkstyle to keep the style more consistent. (Damn tabs everywhere)

### CODE REVIEW

**Comment by NathanWolf** [comment]
Wow, this looks like a ton of work, thanks for doing all of that. Sorry to see that there are already conflicts...

And oops yeah I forgot about the getMage() case of not being loaded yet- I really thought it couldn't return null. Sorry .. yeah I think a throws is a good call there, leave it up to the caller (which is often some other plugin in the case of being called before initializing). I guess if it ends up being an issue we can remove the annotation, but the intention with getMage is that you can rely on it returning a Mage.

As for the style.. yeah I am a tabs guy :P   But I am also a 
{
  matched brackets
}
guy so I guess there's a special place in Java hell for me.

I would not be opposed to making git annotate a bit harder to use in exchange for a mass reformatting at some point, maybe whenever you're ready to add checkstyle. I'd just need to make sure my IDE was set up to follow the style.

**Comment by NathanWolf** [comment]
I guess I should've merged this one before the import cleanup :(

**Comment by killme** [comment]
This is not ready yet. I just did the imports first so the heavy lifting was out of the way.

**Comment by NathanWolf** [comment]
Understood, I just meant maybe I should've waited on the imports since it looks like it caused some merge conflict hell here.

**Comment by killme** [comment]
Just a bit of manual labor, just like adding `@Nullable` all over the place ;)

**Comment by killme** [comment]
Added in b7a4065

**Comment by NathanWolf** [comment]
Awesome, thank you.

What would you say to me doing a global tabs->spaces commit?

**Comment by NathanWolf** [comment]
Um well I was gonna just use my IDE but I like that regex, that'll only do them at the start of a line?

**Comment by killme** [comment]
Nope

**Comment by NathanWolf** [comment]
Oh, duh, right the s is just the sed format. I would just do "\t" -> "    " using a global search and replace in my IDE but I think it'll amount to the same thing. I already did it in MagicWorlds and other than nuking the first level of commit history for every file it seemed to work fine.

I have turned on whitespace in my IDE and indeed I am ashamed by what an insane mix of tabs and spaces are in all these files :(

**Comment by killme** [comment]
I guess a global find and replace will work fine, make sure to pull first of course ;)

**Comment by NathanWolf** [comment]
Am I reading your sed line wrong, or were you suggesting to replace tabs with 1 space? I want 4, right... ?

**Pull request closed without merging**
